services:
  - type: web
    name: labmetricas-backend
    env: java
    plan: starter
    region: oregon
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/LabMetricas-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-17-openjdk-amd64
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://labmetricas.com.mx
      - key: RESEND_DEFAULT_SENDER
        value: noreply@labmetricas.com.mx
      - key: RESEND_DOMAIN
        value: labmetricas.com.mx
    healthCheckPath: /api/health
    autoDeploy: true
